<template><main class="page-shell"><section class="page-hero"><div class="section-container"><h1 class="page-hero-title">Daftar Layanan Dental</h1><p class="page-hero-subtitle">Pilih perawatan sesuai kebutuhan.</p></div></section><section class="page-section"><div class="mb-4"><select v-model="sortKey" class="surface-input max-w-xs"><option value="newest">Terbaru</option><option value="impact-high">Impact Tertinggi</option><option value="duration-fast">Durasi Tercepat</option></select></div><div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3"><article v-for="item in paginated" :key="item.post_id" class="page-panel"><h3 class="text-xl font-bold">{{ item.post?.title }}</h3><p class="text-sm text-slate-600">{{ item.post?.excerpt }}</p></article></div></section></main></template>
<script setup>
import { ref, computed, onMounted } from 'vue'; import axios from 'axios'; import API_ENDPOINTS from '@/config/api';
const LISTING_TYPE = window.LISTING_TYPE || 1; const sortKey = ref('newest'); const listings = ref([]); const currentPage = ref(1); const pageSize = 9;
const getValueByTags = (listing, tags) => { const values = listing?.values || []; const row = values.find(item => tags.includes((item?.tag_name || '').toLowerCase())); return row?.value ?? ''; };
const toNumber = (raw) => { if (raw === null || raw === undefined) return 0; if (typeof raw === 'number') return Number.isFinite(raw) ? raw : 0; const normalized = String(raw).replace(',', '.'); const match = normalized.match(/-?\d+(\.\d+)?/); return match ? parseFloat(match[0]) : 0; };
const getImpactScore = (listing) => { const fromTags = getValueByTags(listing, ['impact', 'dampak', 'impact_score', 'dampak_utama', 'hasil']); const fromPrice = toNumber(listing?.price); return toNumber(fromTags) || fromPrice || 0; };
const getDurationInDays = (listing) => { const durationRaw = getValueByTags(listing, ['durasi', 'duration', 'project_duration', 'lama_proyek']); if (!durationRaw) return Number.MAX_SAFE_INTEGER; const value = toNumber(durationRaw); const text = String(durationRaw).toLowerCase(); if (!value) return Number.MAX_SAFE_INTEGER; if (text.includes('tahun')) return value * 365; if (text.includes('minggu')) return value * 7; if (text.includes('hari')) return value; return value * 30; };
const sorted = computed(() => { const rows = [...listings.value]; if (sortKey.value === 'impact-high') return rows.sort((a, b) => getImpactScore(b) - getImpactScore(a)); if (sortKey.value === 'duration-fast') return rows.sort((a, b) => getDurationInDays(a) - getDurationInDays(b)); return rows.sort((a, b) => new Date(b?.created_at || 0) - new Date(a?.created_at || 0)); });
const paginated = computed(() => sorted.value.slice((currentPage.value - 1) * pageSize, currentPage.value * pageSize));
const fetchListings = async () => { try { const res = await axios.get(API_ENDPOINTS.listings, { params: { listing_type: LISTING_TYPE } }); const data = res?.data?.data || res?.data || []; listings.value = data.filter(listing => listing.listing_type === LISTING_TYPE); } catch { listings.value = []; } };
onMounted(() => fetchListings());
</script>
